name: Multi Arch - ToBeDone.Services.Work

on:
  workflow_dispatch:
      inputs:
        reason:
          description: 'The reason for running the workflow'
          required: true
          default: 'Manual run'
    
env:
  IMAGE_ID: ghcr.io/mumby0168/to-be-done/work-service

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
          packages: write
          contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: src/ToBeDone.Services.Work/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.IMAGE_ID }}:${{ github.sha }},${{ env.IMAGE_ID }}:latest

      

    
