name: Workspaces Service Deploy

on:
  push:
    tags:
     - workspaces-service-v*
    
env:
  IMAGE: to-be-done/workspaces-service

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      img_ver: ${{ steps.version_num.outputs.match }}
    steps:
      - name: Print Tag Ref
        run: echo $GITHUB_REF
      
      - name: Extract Version Number
        uses: actions-ecosystem/action-regex-match@v2
        id: version_num
        with:
          text: ${{ github.ref }}
          regex: '[0-9.]+'

  build:
    needs: version
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
          packages: write
          contents: read

    steps:

      - name: Print Version Number
        run: echo "Version Number ${{ needs.version.outputs.img_ver }}"

      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Docker
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker buildx build . --platform linux/amd64,linux/arm64 -f src/ToBeDone.Services.Workspaces/Dockerfile -t $IMAGE_ID:${{ needs.version.outputs.img_ver }} --output type=image,push=true

  preview:
    needs:
        - version
        - build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0

      - name: Preview
        working-directory: ./infra/ToBeDone.Infra.WorkspacesService
        run: |
              pulumi preview --stack dev --diff -c image=ghcr.io/mumby0168/to-be-done/workspaces-service:${{ needs.version.outputs.img_ver }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy:
    needs:
      - version
      - build
      - preview
    environment: dev
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2.0.0
      
      - name: Pulumi Up
        working-directory: ./infra/ToBeDone.Infra.WorkspacesService
        run: |
              pulumi up --stack dev -c image=ghcr.io/mumby0168/to-be-done/workspaces-service:${{ needs.version.outputs.img_ver }} --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        