name: Work Service Deploy

on:
  push:
    tags:
     - work-service-v*
    
env:
  IMAGE: to-be-done/work-service
  IMAGE_VERSION: n/a

jobs:

  version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag Ref
        run: echo $GITHUB_REF
      
      - name: Extract Version Number
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.ref }}
          regex: '[0-9.]+'

      - name: Set Version Number
        run: |
          IMAGE_VERSION=${{ steps.regex-match.outputs.match }}

      - name: Print Version Number
        run: echo $VERSION

  build:
    needs: version
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
          packages: write
          contents: read

    steps:

      - name: Print Version Number
        run: echo $VERSION

      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Docker Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Docker
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker buildx build . --platform linux/amd64,linux/arm64 -f src/ToBeDone.Services.Work/Dockerfile -t $IMAGE_ID:$IMAGE_VERSION --output type=image,push=true
        

      

    
